### ISSUE TITLE
Classes required for updating Total field

### ISSUE THREAD

**Issue by ylkyrg** [MoshCat/gravityforms-bootstrap-hooks#2]
I had an issue whereby the Total field was not updating based on the Product and Quantity fields.

https://github.com/basmiddelham/gravityforms-bootstrap-hooks/blob/b54e104fa2b777c688110e0e20b66d4fff8f674c/gravityforms.php#L86-L88

Adding these classes back fixed the issue.

```php
// Number fields.
$content = str_replace( 'ginput_quantity', 'ginput_quantity form-control', $content );
$content = str_replace( 'ginput_amount', 'ginput_amount form-control', $content );
```

**Comment by basmiddelham** [comment]
Thank you, this had been added.
